<?php 


echo '<TABLE border=1 cellpadding="0" cellspacing="0" width="90%">
			    <tr>
                            <td colspan=3 bgcolor="#00479e" align="CENTER" style="font-family:arial;font-size:14px;font-weight:bold;color:#FFF"><b>Leads Generated by Suppliers (All)</b></td>
                            </tr>
			    <tr>
			    <TD width="33%" BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >Direct Leads</TD>
                            <TD width="33%" BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >FENQ Leads</TD>
                            <TD width="34%" BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >Unique Buyer</TD>			   
			    </tr>
			    <tr>
			     <TD width="33%" BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >'.$count1.'</TD>
			    <TD width="33%" BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >'.$count2.'</TD>
                             <TD width="34%" BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >'.$count20.'</TD>   
			    </tr>
                             </table>
			    <br>
                           <TABLE border=1 cellpadding="0" cellspacing="0" width="90%">
                            <tr>
                            <td colspan=3 bgcolor="#00479e" align="CENTER" style="font-family:arial;font-size:14px;font-weight:bold;color:#FFF"><b>Leads Approved by Suppliers (All)</b></td>
                            </tr>
			    <tr>
			    <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >Direct Leads</TD>
                            <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >FENQ Leads</TD>
                            <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >Unique Buyers</TD>
			   
			    </tr>
			    <tr>
			    <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >'.$count3.'</TD>
			    <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >'.$count4.'</TD>
                             <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >'.$count17.'</TD>    
			    </tr>			   
			    </table>
			    <br>
			    <table width="90%">
			    <tr>
			     <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >&nbsp;&nbsp;Count of Total Leads (Direct BL + FENQ) Generated by All Suppliers:<div id="show_data7">( <a href="javascript:void(0);" onclick="ShowDemandData(1,\'SAAB\');" style="text-decoration:none;">Show Detail</a> )</div></TD>
			    </tr>
			    <tr><td>
			    <div id="demand_data7"></div></td>
			    <tr>
			    <br>
			  <table border="1" bordercolor="#141907" cellspacing="0" width=90%>	
			    <tr>
			    <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" colspan="3">&nbsp;&nbsp;Total Unique Count of companies - Leads Approved:<div id="show_data8">( <a href="javascript:void(0);" onclick="ShowDemandData(2,\'SAAB\');" style="text-decoration:none;">Show Detail</a> )</div></TD></tr>
			    <tr>
			    <td colspan="3"><div id="demand_data8"></div></td>
			    </tr>';
			    
			   
		    
			    echo '
			    <br>
			    <tr>
			    <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" colspan="2">&nbsp;&nbsp;Direct Lead Rejection Reasons:<div id="show_data9">( <a href="javascript:void(0);" onclick="ShowDemandData(3,\'SAAB\');" style="text-decoration:none;">Show Detail</a> )</div></TD>
			    </tr>
			    <tr>
			    
			    
			     <td colspan="2"><div id="demand_data9"></div></td>
			    
			    </tr>
			    </TABLE>
			    <br>
			    <TABLE>
			    <tr>
			    <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" >Count of Products We Buy:<div id="show_data10">( <a href="javascript:void(0);" onclick="ShowDemandData(4,\'SAAB\');" style="text-decoration:none;">Show Detail</a> )</div></TD>
			    <TD BGCOLOR="#FEFCFF" STYLE="font-family:arial;font-size:14px;" ></TD>
			    </tr>
			    <tr>
			    <td><div id="demand_data10"></div></td>
			    </tr>
			    </TABLE>
			    </tbody></TABLE>';
	 
       
?>